// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlK92g7FWagwYsbYDhcTiB1i6TIK8SXNw',
    appId: '1:118784967487:web:988e4807d513110b50098a',
    messagingSenderId: '118784967487',
    projectId: 'shopapp-58f10',
    authDomain: 'shopapp-58f10.firebaseapp.com',
    storageBucket: 'shopapp-58f10.appspot.com',
    measurementId: 'G-TZ8SR62BB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7sj7RAFtBm3AcgdoAaIhZvVDXhukXTZg',
    appId: '1:118784967487:android:cfc392635f6f36f750098a',
    messagingSenderId: '118784967487',
    projectId: 'shopapp-58f10',
    storageBucket: 'shopapp-58f10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Y62-fEsBmbXAzoLIeaa84S6WN173RSU',
    appId: '1:118784967487:ios:c4fb63143c8eceb950098a',
    messagingSenderId: '118784967487',
    projectId: 'shopapp-58f10',
    storageBucket: 'shopapp-58f10.appspot.com',
    iosClientId: '118784967487-9hu33mgraasu85occs68lcrovdda46me.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodapp',
  );
}
